"use client";

import { useState } from "react";
import PageHeader from "@/components/layout/PageHeader";
import DDPromptPanel from "@/components/dd/DDPromptPanel";
import DDReportHeader from "@/components/dd/DDReportHeader";
import DDReportSection from "@/components/dd/DDReportSection";
import ReviewPanel from "@/components/dd/ReviewPanel";
import { useDDAgent } from "@/hooks/useDDAgent";
import { downloadDDReport } from "@/lib/api";
import type { DDReport } from "@/lib/types";

export default function DDAgentPage() {
  const [prompt, setPrompt] = useState(
    "Our company wants to invest ¥2B in TechCorp KK. Please conduct full legal due diligence as our lawyer."
  );
  const [jurisdiction, setJurisdiction] = useState("JP+US");
  const { status, currentStep, report, error, taskId, runAgent, approveReport } = useDDAgent();

  const handleRun = () => {
    if (!prompt.trim() || status === "running") return;
    runAgent({ prompt, jurisdiction, document_ids: [], transaction_type: "investment" });
  };

  const ddReport = report as DDReport | null;
  const riskSummary = ddReport?.summary
    ? {
        critical: ddReport.summary.critical,
        high: ddReport.summary.high,
        medium: ddReport.summary.medium,
        low: ddReport.summary.low,
      }
    : undefined;

  return (
    <div className="flex h-full">
      <DDPromptPanel
        prompt={prompt}
        jurisdiction={jurisdiction}
        status={status}
        currentStep={currentStep}
        onPromptChange={setPrompt}
        onJurisdictionChange={setJurisdiction}
        onRun={handleRun}
      />

      {/* Right panel */}
      <div className="flex-1 overflow-y-auto bg-[#F5F6F8]">
        <PageHeader
          title="Due Diligence Agent"
          subtitle="LangGraph · 8-step CFI format · JP/US jurisdiction"
          right={
            status === "complete" && ddReport ? (
              <button
                onClick={() => taskId && downloadDDReport(taskId)}
                className="text-[12px] px-4 py-2 rounded-lg font-semibold transition-colors"
                style={{ background: "#2D4FD6", color: "#fff" }}
              >
                Export PDF
              </button>
            ) : null
          }
        />

        <div className="p-6">
          {error && (
            <div className="mb-4 p-3 rounded-lg text-[12px] text-red-600 bg-red-50 border border-red-200">
              {error}
            </div>
          )}

          {/* Human review panel — shown when awaiting attorney approval */}
          {status === "awaiting_review" && (
            <ReviewPanel
              taskId={taskId ?? ""}
              riskSummary={riskSummary}
              onApprove={(notes, approved) => approveReport(notes, approved)}
            />
          )}

          {status === "idle" && (
            <div className="flex flex-col items-center justify-center h-[60vh] text-center">
              <div className="text-5xl mb-4">🔍</div>
              <h3
                className="text-[22px] text-[#111827] mb-2"
                style={{ fontFamily: "var(--font-dm-serif)" }}
              >
                Due Diligence Agent
              </h3>
              <p className="text-[14px] text-[#6B7280] max-w-sm leading-relaxed">
                Enter a DD instruction in the left panel and click{" "}
                <strong>Run DD Agent</strong> to generate a full 8-section CFI due diligence report.
              </p>
            </div>
          )}

          {(status === "running" || status === "complete" || status === "awaiting_review") &&
            ddReport && (
              <>
                <DDReportHeader report={ddReport} />
                <div className="flex flex-col gap-3">
                  {ddReport.sections.map((section) => (
                    <DDReportSection
                      key={section.num}
                      section={section}
                      defaultOpen={section.num === "01" || section.num === "08"}
                    />
                  ))}
                </div>

                <div
                  className="mt-5 p-4 rounded-lg text-[11px] text-[#9CA3AF] leading-relaxed"
                  style={{ background: "#F9FAFB", border: "1px solid #F3F4F6" }}
                >
                  <strong className="text-[#6B7280]">Attorney Disclaimer:</strong> This report is
                  generated by an AI system for internal research purposes only. It does not
                  constitute legal advice. All findings must be reviewed and verified by a licensed
                  attorney before reliance.
                </div>
              </>
            )}

          {status === "running" && !ddReport && (
            <div className="flex flex-col items-center justify-center h-[50vh]">
              <div className="text-[14px] text-[#6B7280]">Running due diligence analysis…</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
