"""Contract review → DOCX with tracked-change-style redlining using python-docx."""

import io
from typing import List

from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


def build_redlined_docx(task: dict) -> bytes:
    """Build a DOCX redline document from a contract review task."""
    doc = Document()
    _set_document_style(doc)

    # ── Title block ────────────────────────────────────────────────────────
    title = doc.add_heading("Contract Review — Redlined Draft", level=1)
    title.runs[0].font.color.rgb = RGBColor(0x2D, 0x4F, 0xD6)

    meta = doc.add_paragraph()
    meta.add_run(f"Document ID: {task.get('task_id', 'N/A')}  |  "
                 f"Status: {task.get('status', 'N/A')}  |  "
                 f"Date: {_today()}")
    meta.runs[0].font.size = Pt(8)
    meta.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()

    # ── Diff view ─────────────────────────────────────────────────────────
    doc.add_heading("Redlined Contract", level=2)

    original = task.get("original_text", "")
    reviewed = task.get("reviewed_text", "")

    if original and reviewed:
        _write_diff_paragraphs(doc, original, reviewed)
    elif original:
        p = doc.add_paragraph(original)
        p.runs[0].font.size = Pt(9)
    else:
        doc.add_paragraph("[No contract text available]")

    # ── Clause annotations ────────────────────────────────────────────────
    clause_reviews = task.get("clause_reviews") or []
    if clause_reviews:
        doc.add_page_break()
        doc.add_heading("Clause Annotations", level=2)
        for clause in clause_reviews:
            _write_clause_annotation(doc, clause)

    # ── Compliance flags ──────────────────────────────────────────────────
    flags = task.get("compliance_flags") or []
    if flags:
        doc.add_heading("Compliance Flags", level=2)
        for flag in flags:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(str(flag)).font.size = Pt(9)

    # ── Disclaimer ────────────────────────────────────────────────────────
    doc.add_paragraph()
    disc = doc.add_paragraph(
        "DISCLAIMER: This document is generated by an AI system for internal research "
        "purposes only. It does not constitute legal advice."
    )
    disc.runs[0].font.size = Pt(8)
    disc.runs[0].font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)
    disc.runs[0].font.italic = True

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _write_diff_paragraphs(doc: Document, original: str, reviewed: str) -> None:
    """Write a simple line-diff with green (added) and red (removed) runs."""
    orig_lines = original.splitlines()
    rev_lines = reviewed.splitlines()

    import difflib
    matcher = difflib.SequenceMatcher(None, orig_lines, rev_lines)
    for op, i1, i2, j1, j2 in matcher.get_opcodes():
        if op == "equal":
            for line in orig_lines[i1:i2]:
                p = doc.add_paragraph(line)
                if p.runs:
                    p.runs[0].font.size = Pt(9)
        elif op in ("replace", "delete"):
            for line in orig_lines[i1:i2]:
                p = doc.add_paragraph()
                run = p.add_run(line)
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)
                run.font.strike = True
        if op in ("replace", "insert"):
            for line in rev_lines[j1:j2]:
                p = doc.add_paragraph()
                run = p.add_run(line)
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(0x16, 0xA3, 0x4A)
                run.bold = True


def _write_clause_annotation(doc: Document, clause: dict) -> None:
    risk = clause.get("risk", "low")
    risk_colors = {
        "critical": RGBColor(0xDC, 0x26, 0x26),
        "high":     RGBColor(0xEA, 0x58, 0x0C),
        "medium":   RGBColor(0xD9, 0x77, 0x06),
        "ok":       RGBColor(0x16, 0xA3, 0x4A),
        "low":      RGBColor(0x6B, 0x72, 0x80),
    }
    p = doc.add_paragraph()
    badge = p.add_run(f"[{risk.upper()}] ")
    badge.font.color.rgb = risk_colors.get(risk, risk_colors["low"])
    badge.bold = True
    badge.font.size = Pt(9)

    ref_run = p.add_run(f"{clause.get('clauseRef', '')} — {clause.get('title', '')}:  ")
    ref_run.font.size = Pt(9)
    ref_run.bold = True

    notes_run = p.add_run(clause.get("notes", ""))
    notes_run.font.size = Pt(9)


def _set_document_style(doc: Document) -> None:
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)


def _today() -> str:
    from datetime import datetime
    return datetime.utcnow().strftime("%Y-%m-%d")
